### ISSUE TITLE
Data Vault bug during decoding with get_parameters() function

### ISSUE THREAD

**Issue by xiaoyuejin** [afylab/afyservers-py3#1]
@arpucsb I see that you had a commit on datavault/backend.py on Jul 30, to fix an issue with add_parameter() function. But is the issue really fixed?

It seems that now you can add a parameter to the dataset (encoding problem solved), but when you want to read it out, you will get a decoding issue.

https://github.com/afylab/afyservers-py3/blob/197ba023f1bc9d2260c3d63a6cbbaa0bebf76398/datavault/backend.py#L58-L60

Two lines (59-60) were added, but the error occurs on line 58 in my test:

dv.get_parameters()
......
>   File "C:\LabRAD\LabRAT\labrad\servers\datavault\backend.py", line 58, in labrad_urldecode
>     **t, data_bytes = T.unflatten(all_bytes, 'ss')**
>   File "C:\LabRAD\WinPython 3.9.8.0\python-3.9.8.amd64\lib\site-packages\labrad\types\types.py", line 307, in unflatten
>     return t.__unflatten__(s, endianness)
>   File "C:\LabRAD\WinPython 3.9.8.0\python-3.9.8.amd64\lib\site-packages\labrad\types\types.py", line 979, in __unflatten__
>     return tuple(unflatten(s, t, endianness) for t in self.items)
>   File "C:\LabRAD\WinPython 3.9.8.0\python-3.9.8.amd64\lib\site-packages\labrad\types\types.py", line 979, in <genexpr>
>     return tuple(unflatten(s, t, endianness) for t in self.items)
>   File "C:\LabRAD\WinPython 3.9.8.0\python-3.9.8.amd64\lib\site-packages\labrad\types\types.py", line 307, in unflatten
>     return t.__unflatten__(s, endianness)
>   File "C:\LabRAD\WinPython 3.9.8.0\python-3.9.8.amd64\lib\site-packages\labrad\types\types.py", line 689, in __unflatten__
>     n = struct.unpack(endianness + 'i', s.get(4))[0]
> struct.error: unpack requires a buffer of 4 bytes

So did the get_parameters() function ever work for you after the commit? Or is there some workaround?

My environment: python 3.9.8, pylabrad 0.98.2.

Any reply is helpful!

**Comment by arpucsb** [comment]
@xiaoyuejin The issue seemed to be that when the parameter was written through add_parameter it wasn't properly encoded, I have fixed it so that parameters are properly saved and added a work around so that it should be able to read parameters in datasets created before the bugfix.

**Comment by arpucsb** [comment]
Issue was patched in [this commit](https://github.com/afylab/afyservers-py3/commit/d5fab12f75d1ce4b9346501ea8be77ceb1f68f56) (made from my old account, whoops).

**Comment by xiaoyuejin** [comment]
@arpucsb I found the problem myself and fixed it in almost the same way... In your code, the "replace" could potentially cause complications. Since the parts need to be removed are always at the beginning and at the end, I suggest using data_url[2:-1], or data_url.removeprefix("b'").removesuffix("'") if you think the [2, -1] looks not decent.
